name: CustomMessages
version: '${version}'
main: com.itsjambo.custommessages.CustomMessages
api-version: '1.16'
commands:
  cmessages-reload:
    description: Reload the plugin configuration
    usage: /cmessages-reload
    aliases: [cm]
    permission: custommessages.reload